#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "gold_miner"

channel = ARGV.first || "dev"

GoldMiner
  .mine_in(channel)
  .fmap { |messages| puts GoldMiner.convert_messages_to_blogpost(channel, messages) }
  .or { |error| abort "[ERROR] #{error}" }
