#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "gold_miner"
require "dotenv"

def load_env_file
  Dotenv.load!
  Dry::Monads::Success()
rescue Errno::ENOENT
  Dry::Monads::Failure("Could not load env file #{env_file.inspect}")
end

def prepare
  load_env_file
    .bind { GoldMiner::Slack::Client.build(api_token: ENV["SLACK_API_TOKEN"]) }
    .fmap { |slack_client|
      GoldMiner::SlackExplorer.new(slack_client, GoldMiner::AuthorConfig.default)
    }
end

channel = ARGV.first || "dev"

prepare.bind { |slack_explorer|
  GoldMiner
    .new(
      explorer: slack_explorer,
      smith: GoldMiner::BlogPostSmith.new,
      distributor: GoldMiner::TerminalDistributor.new
    )
    .mine(channel, start_on: GoldMiner::Helpers::Time.last_friday)
}
  .or { |error| abort "[ERROR] #{error}" }
